### ISSUE TITLE
Recipes Do's and Don'ts

### ISSUE THREAD

**Issue by gordalina** [deployphp/recipes#11]
This issue comes from #10, where rsync (as an alternative deployment method) exposes and overwrites certain tasks and even the `deploy` task.

We can either allow a recipe to override tasks, which is much easier for the end-user which is just plug and play.
On the other hand, for custom deploy scripts, overriding tasks can become an issue, where end-users want a specific task but it is overridden by a recipe.
Also, it could be argued that different deployment methods (such as rsync) could be on deployer itself (rather than recipes). But this will suffer from the same issue (overriding tasks and the `deploy` process)

Currently all recipes expose tasks and on the documentation say how/where they should be added to the deploy process.

This is a major discussion as it will steer the 3rd party recipes and usage of these in the `deployer` project.

Comments are welcome @deployphp/maintainer @elfet @johnny-bit

**Comment by elfet** [comment]
> I think too, what 3rd-party recipes should has no effect on.
> Imagine i has Symfony app based on `recipe/symfony.php`, but i want to use rsync. Now if i require this recipe - my deploy will be broken. Sad =(.

**Comment by johnny-bit** [comment]
sooo I went ahead and changed `rsync.php` into type 1. now rsync is a useful task :smiley:

Now... to shared hosting workflow!

**Comment by johnny-bit** [comment]
So to sum up some suggestions from #10 and #12:

- use short file names.  Eg `ftp` instead of `ftp_upload_to_server_recype_by_me`
- prefix tasks with recipe name. if You have task named `mytest` in `myrecipe` it should be named `myrecipe:mytest`
- use global settings keyed by your recipe name. If You have one setting, name it the same as Your recipe. If You have multiple settings, use associative array
- use environment variables prefixed by Your recipe name. If You have environment  varaible named `better_path` in recipe `myrecipe`, call it `myrecipe_better_path`

did I miss something?

**Comment by gordalina** [comment]
that looks about right :)

**Comment by elfet** [comment]
Good :+1:
