### ISSUE TITLE
phinx recipe does not work under PHP 7+

### ISSUE THREAD

**Issue by bonndan** [deployphp/recipes#83]
The closuritis suffers from backward incompatible changes, see 

http://php.net/manual/en/migration70.incompatible.php
"Changes to the handling of indirect variables, properties, and methods"

```
PHP Warning:  Missing argument 1 for Deployer\{closure}() in vendor/deployer/recipes/phinx.php on line 69
PHP Warning:  Missing argument 2 for Deployer\{closure}() in vendor/deployer/recipes/phinx.php on line 69
PHP Notice:  Undefined variable: cmdName in vendor/deployer/recipes/phinx.php on line 72
PHP Notice:  Undefined variable: conf in vendor/deployer/recipes/phinx.php on line 76
PHP Warning:  Invalid argument supplied for foreach() in vendor/deployer/recipes/phinx.php on line 76
PHP Fatal error:  Uncaught Error: Call to undefined function /var/www/html/daniel/releases/21/vendor/robmorgan/phinx/bin/phinx () in vendor/deployer/recipes/phinx.php:126
Stack trace:
#0 [internal function]: Deployer\{closure}()
#1 phar:///usr/local/bin/dep/src/Task/Task.php(91): call_user_func(Object(Closure))
#2 phar:///usr/local/bin/dep/src/Executor/SeriesExecutor.php(40): Deployer\Task\Task->run(Object(Deployer\Task\Context))
#3 phar:///usr/local/bin/dep/src/Console/TaskCommand.php(79): Deployer\Executor\SeriesExecutor->run(Array, Array, Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Deployer\Console\Output\OutputWatcher))
#4 phar:///usr/local/bin/dep/vendor/symfony/console/Command/Command.php(256): Deployer\Console\TaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///usr/local/bin/dep/vendor/symfony/console/Application.php(820): Symfony\Component\Console\Command\Command->run(Object(Symfony\C in vendor/deployer/recipes/phinx.php 

```

**Comment by elfet** [comment]
@bonndan can you create PR for it?

**Comment by bonndan** [comment]
Really sorry, no. I would like to contribute, but have no time to fix it. My workaround is to call phinx via "run" and that works for now.

**Comment by ket4yii** [comment]
It happens because in the code, two 'sets' stores util functions as closures. Roughly said, it's kind of a currying. I've done it according to [this](https://github.com/deployphp/recipes/pull/54#issuecomment-222492113). As I understood, he meant functions, that's not in closures, can pollute the scope. But in the current version of deployer I don't think it's relevant(because of namespace). There are two ways to fix it:

1. Just make the functions from the 'sets' as normal function: ```function phinx_get_allowed_config($allowedOptions) { ... }``` e.g.
2. Use call_user_func. It will be looks like: ```call_user_func(get('phinx_get_allowed_config'), $ALLOWED_OPTIONS);```

But the second one looks very ugly.

**Comment by ENM1989** [comment]
The second solution does not work, because in Server/Environment::get call_user_func will always be called without the "parameter" parameter. Server/Environment::get does only work with callables without parameters.

I think the first solution is the best one.

Otherwise, the implementation of "getCallable" and "setCallable" would be an option.
